### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by Ferrick90** [szweier/SZMentions#1]
My project is using Swift but I harder to implement to my project. Possible do an example in swift?

**Comment by szweier** [comment]
I'll be starting on a Swift version soon. Will keep you posted when it's available.

**Comment by szweier** [comment]
@Ferrick90 a first version of SZMentionsSwift has been put up that you can locate here: https://github.com/szweier/SZMentionsSwift Please note this is a first version and tests have not yet been written. If you run into issues with the code please feel free to report issues on that repo.

**Comment by Ferrick90** [comment]
Thanks @szweier :+1:

**Comment by szweier** [comment]
Closing this issue. Feel free to make new issues if bugs arise.
