### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by juliankauai** [szweier/SZMentions#11]
# import <SZMentions/SZMentionsListener.h>

/Users/me/Downloads/SZMentions-master/SZMentionsExample/SZMentionsExample/Classes/SZExampleMention.h:9:9: 'SZMentions/SZMentionsListener.h' file not found

can you give me a suggestion?

thanks

julian

**Comment by szweier** [comment]
Sorry for the delay here, can you provide more information as to your setup and what the import statement you currently have in the app look like?

**Comment by szweier** [comment]
@juliankauai did you figure out the issue?  Planning to close this if there's no response in the next couple of days.

**Comment by juliankauai** [comment]
thanks, i figured it out.

**Comment by szweier** [comment]
okay great.
