### ISSUE TITLE
Bug in iOS 11

### ISSUE THREAD

**Issue by nguyenvantrai2011** [szweier/SZMentions#13]
The swift version [here](https://github.com/szweier/SZMentionsSwift) is okey but this is wrong in iOS 11. Plz help me check this again. Plz refer image bellow: 
<img width="471" alt="screen shot 2017-09-27 at 11 36 55" src="https://user-images.githubusercontent.com/12810357/30896083-9c9be7e4-a378-11e7-9b1b-3e4476fde70c.png">

According I'm trying to pod swift version to my Objective-C project but cannot run

**Comment by szweier** [comment]
Sorry to hear about the issues you're having. Unfortunately this version of SZMentions is no longer being maintained. Can you please open an issue on the Swift version about your issues using it in an Objective-C project with some error messages that you are seeing and I will try to update that library to work along side Objective-C.

**Comment by nguyenvantrai2011** [comment]
@szweier thanks for reply me, I'll make an issue in Swift version
