### ISSUE TITLE
Keyboard Chinese Pinyin Bugs

### ISSUE THREAD

**Issue by Ferrick90** [szweier/SZMentions#2]
Once I changed keyboard input to Chinese Pinyin. Found this: 
![textinput_bugs](https://cloud.githubusercontent.com/assets/6068413/12711957/1607e53e-c8ff-11e5-9b40-0942f118de94.gif)

Regards,
Ferrick

**Comment by szweier** [comment]
I'm not entirely sure what the expectation vs. current implementation is here. Would you be able to add a test as a PR that I could possibly try to fix that way. Thanks.

**Comment by Ferrick90** [comment]
The expectation result should be
![expectation](https://cloud.githubusercontent.com/assets/6068413/12739000/820a9988-c9a0-11e5-90f8-82583b5ce92f.gif)

The keyboard will auto include with blue color when I type wo = 我. Current result becomes w哦 and w don't include with the blue color. Hope you can understand it. My english is not very well.

Thanks.

**Comment by Ferrick90** [comment]
Swift version: Issue come from SZMentionsListener.swift line 153 

textView.attributedText = mutableAttributedString as! NSAttributedString

**Comment by szweier** [comment]
Thanks that helps. I'll take a look and let you know when it's fixed.

**Comment by szweier** [comment]
@Ferrick90 the PRs below contain what I believe to be the fix for this issue.  Please give it a try and let me know that it's working for you.  If it is I will merge it and make a new release.

ObjC - https://github.com/szweier/SZMentions/pull/3
Swift - https://github.com/szweier/SZMentionsSwift/pull/1
